spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sigeev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 horas

server:
  port: 8080
  servlet:
    context-path: /api/v1
