server:
  port: 8080
  servlet:
    context-path: /usuarios

spring:
  application:
    name: event-srv-gestao-usuarios

  datasource:
    url: jdbc:postgresql://localhost:5432/sigeev_usuarios
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:chave-secreta-temporaria-deve-ser-substituida-em-producao}
  expiration: ${JWT_EXPIRATION:3600000}
  refresh-token:
    expiration: ${JWT_REFRESH_EXPIRATION:604800000}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
